### ISSUE TITLE
Add screenshots

### ISSUE THREAD

**Issue by ChShersh** [OlivierSohn/hamazed#2]
Could you please add some screenshots of the game to the README?

Cool project, though!

**Comment by nomeata** [comment]
And a video using http://asciinema.org/

**Comment by OlivierSohn** [comment]
Thanks for the suggestion, I added them now!

2017-12-06 20:13 GMT+01:00 Joachim Breitner <notifications@github.com>:

**Comment by ChShersh** [comment]
@OlivierSohn Thanks! I really like your work :)

**Comment by OlivierSohn** [comment]
Thanks for the appreciation, it was a lot of fun to do, and I was lucky
enough to have a bit of time for myself to work on that every day!

2017-12-06 22:11 GMT+01:00 Dmitry Kovanikov <notifications@github.com>:

**Comment by OlivierSohn** [comment]
@nomeata I didn't know about asciinema, it's quite magic!
